### ISSUE TITLE
Include category in getPublicCalendar response

### ISSUE THREAD

**Issue by sam-fisher** [TheAlphaSchoolSystemPTYLTD/public-calendar-and-notices#1]
We would like to integrate the Public Calendar and Notices API with our school website, however we need to be able to identify the category of each event so that we can identify/colour code them. As such, we would like the event category returned in the response from the getPublicCalendar method.

We could probably do this right now by using the getCategories method, and constructing a call for each category using the getPublicCalendar method, but that makes it a lot more complicated!

**Comment by digistorm-developer** [comment]
We are facing a similar issue here.  If the following changes can be added to the **getPublicCalendar** API method that would be great:

- Include the category in the response payload. Preferred option for us would be to include it as an object with the id and category name attributes otherwise attributes prefixed with category such as: category_id, category_name would do.
- Allow filtering by multiple categories. Preferred option to be provided in comma separated ids otherwise via an array would do. 

Thanks!

**Comment by liamstevens** [comment]
Following this issue up - an update on this would be great as we're still waiting to use this API internally.

**Comment by ricardorusson** [comment]
This item has now been scheduled for Dev and will be available in a future Patch Release.

**Comment by ricardorusson** [comment]
This enhancement has completed testing, and should be available in the next few weeks. The documentation has been updated to reflect this change.
